platform:ios ,'8.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
target 'OBDCheck' do
pod 'MBProgressHUD', '~> 0.8’
pod ‘FMDB’
pod 'Bugly'
pod 'SVProgressHUD'
use_frameworks!
end
